# -*- coding: utf-8 -*-
"""Granite chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10HgW54rsBH8tlQRX4rBvtjJYlYNZexM_
"""

pip install -U transformers

from transformers import pipeline

pipe =pipeline("text-generation", model="ibm-granite/granite-3.3-2b-instruct")
messages=[
{"role":"user","content":"who are you?"},
]
pipe(messages)

# load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer .from_pretrained("ibm-granite/granite-3.3-2b-instruct")
model=AutoModelForCausalLM.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
messages = [
{"role":"user","content":"whi are you?"},
]
inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
    tokenize=True,
    return_dict=True,
    return_tensors="pt",
).to(model.device)

outputs= model.generate(**inputs, max_new_tokens=40)
print(tokenizer.decode(outputs[0][inputs["input_ids"]. shape [-1]:]))

!pip install -q gradio transformers torch black

import gradio as gr
from transformers import pipeline
import torch
import ast
import re
from datetime import datetime
from pathlib import Path
import json
import black
import autopep8
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
import requests
import os

# --- Configuration & Global Variables ---
class ChatbotConfig:
    MODEL_NAME = "ibm-granite/granite-3.3-2b-instruct"
    DEFAULT_TEMP = 0.7
    DEFAULT_MAX_TOKENS = 256
    DEFAULT_TOP_P = 0.95

conversation_history = []
model_pipe = None

# --- Model Loading Logic ---
def load_model():
    global model_pipe
    print("🚀 Loading IBM Granite 3.3 2B Instruct model...")
    device = 0 if torch.cuda.is_available() else -1
    device_type = "GPU" if device == 0 else "CPU"
    print(f"Using: {device_type}")

    model_pipe = pipeline(
        "text-generation",
        model=ChatbotConfig.MODEL_NAME,
        device=device,
        torch_dtype=torch.float16 if device == 0 else torch.float32,
    )
    print("✅ Model loaded successfully!")
    return model_pipe

# --- Code Detection & Syntax Surgeon Utils ---
def detect_python_code(text):
    code_patterns = [
        r'def\s+\w+\s*\(', r'class\s+\w+', r'import\s+\w+',
        r'from\s+\w+\s+import', r'if\s+.*:', r'for\s+.*in\s+', r'while\s+.*:'
    ]
    return any(re.search(pattern, text) for pattern in code_patterns)

def check_syntax(code):
    try:
        ast.parse(code)
        return True, None
    except SyntaxError as e:
        return False, f"Syntax Error (line {e.lineno}): {e.msg}"
    except Exception as e:
        return False, f"Error: {str(e)}"

def fix_code_indentation(code):
    lines = code.split('\n')
    fixed_lines = [line.rstrip().replace('\t', '    ') for line in lines]
    return '\n'.join(fixed_lines)

def fix_code_brackets(code):
    for pair in [('(', ')'), ('[', ']'), ('{', '}')]:
        open_c = code.count(pair[0])
        close_c = code.count(pair[1])
        if open_c > close_c:
            code += pair[1] * (open_c - close_c)
    return code

def format_code(code):
    try:
        return black.format_str(code, mode=black.FileMode())
    except:
        try:
            return autopep8.fix_code(code)
        except:
            return code

def fix_python_code(code):
    code = fix_code_indentation(code)
    code = fix_code_brackets(code)
    is_valid, error_msg = check_syntax(code)
    if not is_valid:
        return {"success": False, "fixed_code": code, "error": error_msg, "message": f"⚠️ Syntax Error: {error_msg}"}
    code = format_code(code)
    return {"success": True, "fixed_code": code, "error": None, "message": "✅ Code fixed successfully!"}

# --- PDF Export Logic ---
def export_chat_pdf():
    if not conversation_history:
        return "❌ Chat is empty!", None

    filename = f"chat_history_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    doc = SimpleDocTemplate(filename, pagesize=letter)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle('TitleStyle', parent=styles['Title'], textColor=colors.hexColor('#2c3e50'), spaceAfter=12)
    user_style = ParagraphStyle('UserStyle', parent=styles['Normal'], textColor=colors.blue, leftIndent=10)
    bot_style = ParagraphStyle('BotStyle', parent=styles['Normal'], textColor=colors.darkgreen, leftIndent=10)

    story = []
    story.append(Paragraph("⚪ Granite Chatbot - Chat History", title_style))
    story.append(Paragraph(f"<b>Exported on:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
    story.append(Spacer(1, 0.2*inch))

    for i, msg in enumerate(conversation_history, 1):
        role = msg['role'].upper()
        content = msg['content'].replace('<', '&lt;').replace('>', '&gt;')

        story.append(Paragraph(f"<b>{role}:</b>", user_style if role == "USER" else bot_style))
        story.append(Paragraph(content, styles['Normal']))
        story.append(Spacer(1, 0.1*inch))

        if i % 5 == 0:
            story.append(PageBreak())

    story.append(Spacer(1, 0.3*inch))
    story.append(Paragraph("<b>End of Chat</b>", styles['Normal']))

    try:
        doc.build(story)
        return f"✅ PDF Generated: {filename}", filename
    except Exception as e:
        return f"❌ Error: {str(e)}", None

# --- Share Link Logic ---
def generate_share_link():
    return "📄 Share Link generation disabled in Colab. Use PDF download."

# --- Main Chat Logic ---
def chat_response(message, history, temp, tokens, top_p):
    global conversation_history
    if not message.strip():
        return history, ""

    conversation_history.append({"role": "user", "content": message})

    if detect_python_code(message):
        fix_res = fix_python_code(message)
        response = f"{fix_res['message']}\n\n**Processed Code:**\n```python\n{fix_res['fixed_code']}\n```"
    else:
        out = model_pipe(message, max_new_tokens=tokens, temperature=temp, top_p=top_p, do_sample=True)
        response = out[0]['generated_text']

    conversation_history.append({"role": "assistant", "content": response})
    history.append((message, response))
    return history, ""

# --- Gradio UI Layout ---
with gr.Blocks(title="Granite Chatbot", theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 💬 Granite Chatbot (Syntax Surgeon Edition)")

    with gr.Row():
        with gr.Column(scale=4):
            chatbot = gr.Chatbot(label="Chat History", height=450)
            msg = gr.Textbox(label="Message / Python Code", placeholder="Type here...", lines=2)
            with gr.Row():
                submit_btn = gr.Button("Send", variant="primary")
                clear_btn = gr.Button("Clear")

        with gr.Column(scale=1):
            gr.Markdown("### ⚙️ Parameters")
            temp = gr.Slider(0.1, 1.0, value=0.7, label="Temperature")
            tokens = gr.Slider(50, 1024, value=256, step=50, label="Max Tokens")
            top_p = gr.Slider(0.1, 1.0, value=0.95, label="Top P")

            gr.Markdown("---")
            gr.Markdown("### 📥 Export")
            pdf_btn = gr.Button("📋 Export PDF")
            pdf_out = gr.File(label="Download PDF")
            status = gr.Textbox(label="Status", interactive=False)

    submit_btn.click(chat_response, [msg, chatbot, temp, tokens, top_p], [chatbot, msg])
    msg.submit(chat_response, [msg, chatbot, temp, tokens, top_p], [chatbot, msg])

    def clear_all():
        global conversation_history
        conversation_history = []
        return [], ""

    clear_btn.click(clear_all, None, [chatbot, msg])
    pdf_btn.click(export_chat_pdf, None, [status, pdf_out])

if __name__ == "__main__":
    load_model()
    demo.launch(share=True)

!pip install reportlab autopep8 black

!pip install black autopep8 reportlab